all:
  hosts:
    master:
      ansible_host: master_ip
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker1:
      ansible_host: worker1_ip
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
    worker2:
      ansible_host: worker2_ip
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
  children:
    masters:
      hosts:
        master:
    workers:
      hosts:
        worker1:
        worker2:
